name: Automatic Releases

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
      pull-requests: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Set up WIN JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          uri: 	https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip 
    
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github

      - name: Build with Maven
        run: mvn package assembly:single

      - name: Delete Package
        run: |
          curl --request DELETE \
          --url https://api.github.com/user/packages/maven/org.mocha.mocha-devkit \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28'

      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>timidtlk</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy

      - name: Publish release files
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: v0.1.0-alpha
          prerelease: true
          title: 0.1a
          files: |
            .github/packr/build/linux64/linux64.zip
            .github/packr/build/windows64/windows64.zip
